<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/6/5 0005
 * Time: 下午 5:25
 */

namespace app\admin\controller;
use think\Config;
use app\common\model\Notice as NoticeModel;
class Notice extends AdminBase {
  protected $noticeMdl;
  protected function _initialize () {
    parent::_initialize(); // TODO: Change the autogenerated stub
    $this->noticeMdl = new NoticeModel();
  }
  
  /**
   * 公告列表
   * @author: slide
   * @param string $keyword
   * @param int    $page
   *
   */
  public function index ($keyword='', $page = 1) {
    $map = [];
    if($keyword){ $map['title'] = ['LIKE', "%{$keyword}%"];}
    $res = $this->noticeMdl->where($map)->paginate(Config::get('pageSize'), false, ['page'=>$page]);
    
    return $this->fetch('index', ['list'=>$res]);
  }
  
  /**
   * 获取单个公告信息
   * @author: slide
   * @param $id
   *
   */
  public function getNoticeById($id){
    if($id){
      $res = $this->noticeMdl->find($id);
      if($res){
        $this->success('获取公告信息成功', '', $res);
      }else{
        $this->error('获取公告信息失败');
      }
    }else{
      $this->error('没有你要的公告信息');
    }
  }
  
  /**
   * 发送公告
   * @author: slide
   * @param $retry 是否重新发送信息
   */
  public function saveNotice($retry = false){
    if($this->request->isPost()){
      $type = input('id') > 0 ? 2 : 1;
      $data = $this->request->post();
      
      $this->noticeMdl->data($data, true);
      $cont = mb_substr(strip_tags($data['content']), 0, 200);
      if($type == 1){
        // 存并发送消息
        $res = $this->noticeMdl->allowField(true)->isUpdate(false)->save();
        // 发消息
        sendSiteMsg(-1,'', $data['title'], $cont, 4,1, json_encode(['id'=>$this->noticeMdl->id]),false, true);
      }else{
        $res = $this->noticeMdl->allowField(true)->isUpdate(true)->save();
        if($retry){
         
          $encode = mb_detect_encoding($cont, array("ASCII","UTF-8","GB2312","GBK","BIG5"));
          sendSiteMsg(-1,'', $data['title'], $cont, 4,1, json_encode(['id'=>$this->noticeMdl->id]),false, true);
          
        }
      }
      if($res){
        $this->success('操作成功');
      }else{
        $this->error('操作失败');
      }
    }else{
      $this->error('访问方式错误');
    }
  }
  
  /**
   * 删除公告
   * @author: slide
   * @param string $id
   * @param string $ids
   *
   */
  public function delete($id='',$ids=''){
    $id = $ids ? $ids : $id;
    if($id){
      $this->request->get();
      if($this->noticeMdl->destroy($id)){
        $this->success('删除成功');
      }else{
        $this->error('删除失败');
      }
    }else{
      $this->error('请选择需要删除的公告');
    }
  }
}
