<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/5/24 0024
 * Time: 上午 10:29
 */

namespace app\agentadmin\controller;


use think\Session;

class Common extends AgentBase {
  protected function _initialize () {
    parent::_initialize(); // TODO: Change the autogenerated stub
    $path_arr = [
      'agentadmin/Order/needpayorderlist',
      'agentadmin/Order/confirm_order',
      'agentadmin/Order/payforchildorder'
    ];
    $path = request()->module().'/'.request()->controller().'/'.request()->action();
    if(in_array($path, $path_arr)){
      // 验证前台登录后者后台登录
      if(!Session::get('qt_userId')&&!$this->checkLogin() ){
        $this->error('您还没有登录呢!', url('login/index'));
      }
      

    }else{
      if(!$this->checkLogin()){
        $this->error('您还没有登录呢!', url('login/index'));
      }
    }
    
  }
  /**
   * 检验登录并把登录信息返回
   * @author: slide
   *
   */
  public function checkLogin(){
    $flag = false;
    if($this->isAgentAdmin()){
      $this->assign('loginInfo', session('agent_admin'));
      $flag = true;
    }else{
      if(session('agent_employee')){
        $this->assign('loginInfo', session('agent_employee'));
        $flag = true;
      }
    }
    
    return $flag;
  }
}
